# ==============================================================================
# IBVAP - ANPR License Plate Dataset Configuration for YOLO Training
# ==============================================================================

path: D:\PROJECTHAILMARY\data\dataset\anpr  # absolute path - avoids Ultralytics relative resolution issues
train: train/images         # train images (relative to 'path')
val: val/images             # val images (relative to 'path')
test: test/images           # test images (optional)

# Classes
names:
  0: license_plate
