# ==============================================================================
# IBVAP - ANPR License Plate Dataset Configuration for YOLO Training
# ==============================================================================

path: ../data/dataset/anpr  # dataset root dir (relative to training script or absolute)
train: train/images         # train images (relative to 'path')
val: val/images             # val images (relative to 'path')
test: test/images           # test images (optional)

# Classes
names:
  0: license_plate
